baseurl = "http://swiftline.github.io"
languageCode = "en-us"
title = "Swiftline"

[params]
    description = "Amazing project."
    author_url = "http://nsomar.com"
    author_name = "NSOmar"
    project_url = "http://github.com/swiftline/swiftline"
    project_documentation = "http://swiftline.github.io/docs"
    github_project_name = "swiftline"
    github_user_name = "swiftline"

    first_color="#f8f8f8"
    first_border_color="#e7e7e7"
    first_text_color="#333"

    second_color="white"
    second_text_color="#333"

    header_color="#f8f8f8"
    header_text_color="rgb(51, 51, 51)"

    header_link_color="#777"
    header_link_hover_color="rgb(51, 51, 51)"
