baseurl = "www.x314.network"
languageCode = "en-us"
title = "Swiftline"

[params]
    description = "Universal Crypto Income"
    author_url = "http://www.x314.network"
    project_url = "http://www.x314.network/members/join"
    project_documentation = "http://www.x314.network/docs"
    github_user_name = "x314network"

    first_color="#f8f8f8"
    first_border_color="#e7e7e7"
    first_text_color="#333"

    second_color="white"
    second_text_color="#333"

    header_color="#f8f8f8"
    header_text_color="rgb(51, 51, 51)"

    header_link_color="#777"
    header_link_hover_color="rgb(51, 51, 51)"
